[tools]
python = "3.13"

[tools.uv]
version = "0.6"
postinstall = "mise run install-local-completions uv generate-shell-completion"

[tools.editorconfig-checker]
version = "3.2.0"

[tools.lefthook]
# renovate: datasource=github-releases depName=evilmartians/lefthook
version = "v1.11.2"
postinstall = 'mise run install-local-completions lefthook completion'

[tools.cocogitto] # TODO: simplify after https://github.com/jdx/mise/pull/4513
# renovate: datasource=github-releases depName=cocogitto/cocogitto
version = "6.2"
postinstall = 'mise run install-local-completions cog generate-completions'

# implement in mise.local.toml or ~/.config/mise.toml
# cf. https://gist.github.com/reitzig/2885464e5c2fcc0f84bda9e1dae4f7b1
# [tasks.install-local-completions]
# hide = true
# run = '<your code>'
