[tools]
python = "3.13"
uv = "0.6"
editorconfig-checker = "3.1"
# renovate: datasource=github-releases depName=evilmartians/lefthook
lefthook = "1.10"
# renovate: datasource=github-releases depName=cocogitto/cocogitto
"aqua:cocogitto/cocogitto" = "6.2" # TODO: simplify after https://github.com/jdx/mise/pull/4513
