[tools]
python = "3.13"
"aqua:astral-sh/uv" = "0.5.23"
# TODO: not used, global config wins out (PATH order)!

# TODO: migrate ../aqua.yaml here?
#       If so, adapt Renovate config!
#       cf. https://github.com/jdx/mise/discussions/1940
